module-name: infrastructure-manager
kind: kcp
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/infrastructure-manager:1.0.3
mend:
  language: golang-mod
  exclude:
    - "**/*_test.go"
checkmarx-one:
    preset: go-default
    exclude:
        - '**/*_test.go'
