# permissions for end users to view runtimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: infrastructure-manager
    app.kubernetes.io/managed-by: kustomize
  name: runtime-viewer-role
rules:
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - runtimes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - runtimes/status
  verbs:
  - get
